import { Product, Category } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "T-Shirts",
    slug: "t-shirts",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop&q=80",
    count: 4,
  },
  {
    id: "2",
    name: "Hoodies & Sweatshirts",
    slug: "hoodies",
    image: "https://images.unsplash.com/photo-1556821840-3a63f15232d6?w=600&auto=format&fit=crop&q=80",
    count: 3,
  },
  {
    id: "3",
    name: "Hats & Caps",
    slug: "hats",
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80",
    count: 2,
  },
  {
    id: "4",
    name: "Accessories",
    slug: "accessories",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
    count: 3,
  },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "grizzlies-classic-tee",
    name: "Grizzlies Classic Tee",
    price: 29.99,
    category: "t-shirts",
    description: "The essential Griz tee, perfect for game day or everyday wear.",
    longDescription:
      "Show your Montana Grizzlies pride with this timeless classic tee. Made from 100% ring-spun cotton for supreme softness, featuring the iconic Grizzlies logo on the chest. Pre-shrunk to ensure a consistent fit wash after wash. Perfect for game day, campus, or casual everyday wear.",
    images: [
  "/universityofmontanatee.jpg",
  "https://images.unsplash.com/photo-1559583985-c80d8ad9b29f?w=800&auto=format&fit=crop&q=80",
],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Maroon", "White", "Heather Grey"],
    inStock: true,
    featured: true,
    badge: "Best Seller",
  },
{
    id: "5",
    slug: "grizzlies-water-bottle",
    name: "Grizzlies Water Bottle",
    price: 34.99,
    category: "accessories",
    description: "Insulated stainless steel water bottle with Grizzlies logo, 32oz.",
    longDescription:
      "Stay hydrated in Griz style with this premium 32oz stainless steel water bottle. Double-wall vacuum insulation keeps drinks cold for 24 hours and hot for 12. The wide mouth opening is easy to fill and clean. Features the Grizzlies logo laser-engraved on the side.",
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559829067-c0aa0fbe8a52?w=800&auto=format&fit=crop&q=80",
    ],
    colors: ["Maroon", "Silver", "Black"],
    inStock: true,
    featured: false,
  },
  {
    id: "2",
    slug: "montana-script-hoodie",
    name: "Montana Script Hoodie",
    price: 64.99,
    salePrice: 54.99,
    category: "hoodies",
    description: "Premium fleece hoodie with the iconic Montana script across the chest.",
    longDescription:
      "Stay warm and stylish with this premium Montana Script Hoodie. Features a bold script 'Montana' design across the chest, kangaroo pocket, and a cozy fleece-lined interior. The drawstring hood and ribbed cuffs provide a snug, comfortable fit. Perfect for cool Montana evenings at the game.",
    images: [
  "/universityofmontanahoodie.jpg",
  "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=800&auto=format&fit=crop&q=80",
],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Maroon", "Navy", "Charcoal"],
    inStock: true,
    featured: true,
    badge: "Sale",
  },
  /*
  {
    id: "3",
    slug: "um-structured-cap",
    name: "UM Structured Cap",
    price: 27.99,
    category: "hats",
    description: "Classic structured cap with embroidered UM logo, adjustable fit.",
    longDescription:
      "Rep the Griz wherever you go with this clean, structured cap. Features an embroidered University of Montana 'M' logo on the front, adjustable strap at the back for a custom fit, and a curved brim. One size fits most. Perfect for keeping the sun out of your eyes at outdoor events.",
    images: [
      "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800&auto=format&fit=crop&q=80",
    ],
    colors: ["Maroon/White", "Navy/White", "Black/Maroon"],
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    slug: "griz-nation-crew-neck",
    name: "Griz Nation Crew Neck",
    price: 49.99,
    category: "hoodies",
    description: "Soft crew neck sweatshirt declaring your allegiance to Griz Nation.",
    longDescription:
      "This comfortable crew neck sweatshirt is a must-have for any Griz fan. The 'Griz Nation' graphic on the front is screen-printed for long-lasting quality. Made with a plush fleece interior for warmth without bulk. A versatile piece that looks great on campus or at the stadium.",
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f15232d6?w=800&auto=format&fit=crop&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Maroon", "Grey"],
    inStock: true,
    featured: true,
    badge: "New",
  },
  {
    id: "6",
    slug: "um-game-day-tee",
    name: "UM Game Day Tee",
    price: 27.99,
    category: "t-shirts",
    description: "Vintage-style graphic tee made for cheering on the Griz.",
    longDescription:
      "Gear up for game day with this vintage-style graphic tee. Features a distressed University of Montana athletic print that gives it an authentic, worn-in look. Made from a soft cotton-poly blend for ultimate comfort during those intense games. Lightweight and breathable for warm tailgate afternoons.",
    images: [
      "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Maroon", "White"],
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    slug: "montana-beanie",
    name: "Montana Beanie",
    price: 22.99,
    category: "hats",
    description: "Cozy knit beanie perfect for those cold Montana winters.",
    longDescription:
      "Brave the Montana cold in style with this premium knit beanie. Features a ribbed design with a fold-up cuff and an embroidered 'M' logo. Made from a warm acrylic blend that's soft against the skin and maintains its shape wash after wash. A staple for any Griz fan braving the elements.",
    images: [
      "https://images.unsplash.com/photo-1510598155916-a806d8ed3f72?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop&q=80",
    ],
    colors: ["Maroon", "Charcoal", "White"],
    inStock: true,
    featured: false,
    badge: "New",
  },
  {
    id: "8",
    slug: "grizzlies-zip-hoodie",
    name: "Grizzlies Full-Zip Hoodie",
    price: 74.99,
    category: "hoodies",
    description: "Premium full-zip hoodie with side pockets and Grizzlies logo.",
    longDescription:
      "Elevate your Griz wardrobe with this premium full-zip hoodie. The full-length zipper provides versatile wear — zip up for warmth or layer open over your game-day tee. Features two side zip pockets and an embroidered Grizzlies logo on the left chest. Made from heavyweight fleece for maximum warmth.",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1556821840-3a63f15232d6?w=800&auto=format&fit=crop&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: ["Maroon", "Black"],
    inStock: true,
    featured: false,
  },
  {
    id: "9",
    slug: "griz-travel-mug",
    name: "Griz Travel Mug",
    price: 24.99,
    category: "accessories",
    description: "16oz ceramic travel mug with Grizzlies logo, microwave safe.",
    longDescription:
      "Start your morning right with this Griz travel mug. The 16oz ceramic construction keeps your coffee or tea warm while looking great on your desk or in the car. Features the iconic Grizzlies logo and a comfortable C-handle. Microwave and dishwasher safe for easy maintenance.",
    images: [
      "https://images.unsplash.com/photo-1572119865084-43c285814d63?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1557787163-1635e2efb160?w=800&auto=format&fit=crop&q=80",
    ],
    colors: ["Maroon", "White"],
    inStock: true,
    featured: false,
  },
  {
    id: "10",
    slug: "grizzlies-premium-polo",
    name: "Grizzlies Premium Polo",
    price: 49.99,
    category: "t-shirts",
    description: "Moisture-wicking performance polo, great for the course or the stands.",
    longDescription:
      "Look sharp in the stands or on the fairway with this premium polo. Features moisture-wicking technology to keep you cool and dry, a two-button placket, and a subtle Grizzlies logo embroidered on the left chest. The performance fabric has UV protection and maintains a crisp look all day.",
    images: [
      "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Maroon", "White", "Navy"],
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    slug: "um-lanyard-keychain",
    name: "UM Lanyard & Keychain Set",
    price: 14.99,
    category: "accessories",
    description: "Durable woven lanyard with detachable keychain, great for campus IDs.",
    longDescription:
      "Keep your student ID, keys, and essentials close with this officially licensed University of Montana lanyard and keychain set. The woven polyester lanyard features UM Grizzlies branding in team colors with a breakaway safety clasp. The matching keychain features the classic 'M' logo.",
    images: [
      "https://images.unsplash.com/photo-1620207418302-439b387441b0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80",
    ],
    colors: ["Maroon/Silver"],
    inStock: true,
    featured: false,
  },
  {
    id: "12",
    slug: "montana-long-sleeve-tee",
    name: "Montana Long-Sleeve Tee",
    price: 34.99,
    salePrice: 29.99,
    category: "t-shirts",
    description: "Classic long-sleeve tee with 'Montana' text along the sleeve.",
    longDescription:
      "Layer up in Griz style with this versatile long-sleeve tee. Features the word 'Montana' printed along the left sleeve for a distinctive look. Made from a soft cotton-polyester blend that feels great against the skin. Ideal for layering under a hoodie on cool days or wearing solo on mild ones.",
    images: [
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&auto=format&fit=crop&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    colors: ["Maroon", "White", "Grey"],
    inStock: true,
    featured: false,
    badge: "Sale",
  },
  */
];
